2024-05-25 16:59:50,145 FILE: __init__.py IN: __threaded_polling MESSAGE: Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-25 16:59:50,180 FILE: __init__.py IN: __threaded_polling MESSAGE: Exception traceback:
Traceback (most recent call last):
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-05-25 16:59:53,889 FILE: __init__.py IN: __threaded_polling MESSAGE: Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-25 16:59:53,895 FILE: __init__.py IN: __threaded_polling MESSAGE: Exception traceback:
Traceback (most recent call last):
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-05-25 16:59:58,055 FILE: __init__.py IN: __threaded_polling MESSAGE: Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-25 16:59:58,057 FILE: __init__.py IN: __threaded_polling MESSAGE: Exception traceback:
Traceback (most recent call last):
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olegb\PycharmProjects\pythonProject52\venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-05-25 20:41:57,250 FILE: __init__.py IN: infinity_polling MESSAGE: Infinity polling: polling exited
2024-05-25 20:41:57,277 FILE: __init__.py IN: infinity_polling MESSAGE: Break infinity polling
